# spring:
#     datasource:
#         driver-class-name: org.mariadb.jdbc.Driver
#         url: jdbc:mariadb://localhost:3306/mariadb
#         username: mariadb
#         password: mariadb
spring:
    datasource:
        url: jdbc:h2:mem:testdb;
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
